language: node_js
node_js:
  - "8"
  - "9"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm test
# added by Sam Chacko (all commeneted out as same as alreadythere.)
# .travis.yml file
# language: node_js
# node_js:
#  - "8"
# services: mongodb
# cache:
#  directories:
#    - "node_modules"
# sudo: false
# install:
  -npm install
# script:
#  - npm test